# Generated by Django 2.2.12 on 2020-05-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homearticle',
            name='photo_ref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
