# Generated by Django 2.2.12 on 2020-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0002_homearticle_photo_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homearticle',
            name='photo_ref',
        ),
        migrations.AddField(
            model_name='homearticle',
            name='videofile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
