# Generated by Django 2.2.12 on 2020-05-22 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0005_homearticle_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='homearticle',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
