# Generated by Django 2.2.12 on 2020-05-25 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0007_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
