# Generated by Django 2.2.12 on 2020-05-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0011_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
