# Generated by Django 2.2.12 on 2020-05-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0012_photo_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='shirt_size',
        ),
    ]
