# Generated by Django 2.2.12 on 2020-05-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0014_auto_20200530_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='article',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
