# Generated by Django 2.2.12 on 2020-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0015_auto_20200530_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='article',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(),
        ),
    ]
