# Generated by Django 2.2.12 on 2020-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0017_auto_20200530_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homearticle',
            name='videofile',
            field=models.FileField(upload_to='images/'),
        ),
    ]
