# Generated by Django 2.2.12 on 2020-05-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0018_auto_20200530_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homearticle',
            name='date',
        ),
        migrations.RemoveField(
            model_name='homearticle',
            name='location',
        ),
        migrations.RemoveField(
            model_name='homearticle',
            name='text',
        ),
        migrations.RemoveField(
            model_name='homearticle',
            name='videofile',
        ),
    ]
