# Generated by Django 2.2.12 on 2020-05-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0019_auto_20200530_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homearticle',
        ),
    ]
