# Generated by Django 2.2.12 on 2020-05-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picarticles', '0020_delete_homearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='article',
            field=models.IntegerField(),
        ),
    ]
