# Generated by Django 2.2.12 on 2020-05-22 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_photos',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
