# Generated by Django 2.2.12 on 2020-05-25 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_photos', '0004_auto_20200524_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='images',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='images',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
