# Generated by Django 2.2.12 on 2020-05-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_photos', '0005_auto_20200525_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='front_images',
        ),
    ]
