# Generated by Django 2.2.12 on 2020-05-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_photos', '0006_auto_20200525_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='front_photos',
        ),
    ]
